import type { Metadata } from "next";
import { Geist, Geist_Mono, Timmana } from "next/font/google";

import "../styles/globals.css"

const timmana = Timmana({
  variable: "--font-timmana",
  subsets: ["latin"],
  display: "swap",
  style: "normal",  
  weight: ["400"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${timmana.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
